import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { PageHeader } from "@/components/ui/page-header";
import { PayButton } from "@/components/customer/pay-button";
import { ButtonLink } from "@/components/ui/button";
import { serverApi } from "@/lib/server-api";
import { formatDate, formatKwh, formatNaira, monthLabel } from "@/lib/format";
import type { Bill } from "@/lib/types";
export default async function BillDetail({params}:{params:Promise<{id:string}>}){const {id}=await params;const {bill}=await serverApi<{bill:Bill}>(`/api/v1/me/bills/${id}`);const rows=[["Previous reading",formatKwh(bill.previous_reading)],["Current reading",formatKwh(bill.current_reading)],["Units consumed",formatKwh(bill.units)],["Tariff rate",`${formatNaira(bill.rate_per_kwh)} / kWh`],["Energy charge",formatNaira(bill.energy_charge)],["Fixed charge",formatNaira(bill.fixed_charge)],[`VAT ${bill.vat_percent ?? "7.5"}%`,formatNaira(bill.vat_amount)],["Total due",formatNaira(bill.total_amount)]];return <div className="space-y-7"><PageHeader eyebrow="ITEMISED BILL" title={`${monthLabel(bill.billing_month)} bill`} description={`Generated from your meter reading. Due ${formatDate(bill.due_date)}.`}/><div className="grid gap-5 lg:grid-cols-[1.25fr_.75fr]"><Card className="p-5 md:p-7"><div className="divide-y divide-line-subtle">{rows.map(([a,b],i)=><div key={a} className="flex items-center justify-between gap-5 py-4"><span className={i===rows.length-1?"font-semibold":"text-sm text-info"}>{a}</span><span className={`data-number text-right ${i===rows.length-1?"text-xl font-bold":"text-sm font-semibold"}`}>{b}</span></div>)}</div></Card><Card className="h-fit p-5 md:p-6"><Badge value={bill.status}/><h2 className="mt-5 font-display text-xl font-bold">Due {formatDate(bill.due_date)}</h2><p className="data-number mt-3 text-3xl font-bold">{formatNaira(bill.total_amount)}</p><div className="mt-6">{bill.status==="paid"?<ButtonLink className="w-full" href={`/receipts/${bill.id}`}>View receipt</ButtonLink>:<PayButton billId={bill.id}/>}</div></Card></div></div>}
