# yaml-language-server: $schema=https://render.com/schema/render.yaml.json
services:
  - type: web
    name: powerflow
    runtime: node
    plan: free
    region: frankfurt
    repo: https://github.com/Cyberforgex-06/PowerFlow
    branch: main
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm run start -- --hostname 0.0.0.0 --port $PORT
    healthCheckPath: /api/health
    autoDeployTrigger: commit
    envVars:
      - key: NODE_VERSION
        value: 24.19.0
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: https://ebbuepdkmhxmkibatsha.supabase.co
      - key: NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY
        sync: false
