"use client";
import { useState } from "react";
import { Plus, Save } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { FieldLabel, Input } from "@/components/ui/field";
import { ApiError, apiRequest } from "@/lib/api";
import type { Tariff } from "@/lib/types";
export function TariffForm({tariff}:{tariff?:Tariff}){const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setMessage("");const fd=new FormData(e.currentTarget);const data={...(tariff?{id:tariff.id}:{}),name:String(fd.get("name")??""),rate_per_kwh:String(fd.get("rate_per_kwh")??""),fixed_charge:String(fd.get("fixed_charge")??""),vat_percent:String(fd.get("vat_percent")??"7.5"),is_active:fd.get("is_active")==="on"};setBusy(true);try{await apiRequest("/api/v1/admin/tariffs",{method:tariff?"PATCH":"POST",body:JSON.stringify(data)});window.location.reload()}catch(e){setMessage(e instanceof ApiError?e.message:"Tariff could not be saved.")}finally{setBusy(false)}}return <form onSubmit={submit}><Card className="p-5"><div className="grid gap-4 md:grid-cols-2"><label><FieldLabel htmlFor={`name-${tariff?.id??"new"}`}>Tariff name</FieldLabel><Input id={`name-${tariff?.id??"new"}`} name="name" defaultValue={tariff?.name??""} required/></label><label><FieldLabel htmlFor={`rate-${tariff?.id??"new"}`}>Rate / kWh</FieldLabel><Input id={`rate-${tariff?.id??"new"}`} name="rate_per_kwh" inputMode="decimal" defaultValue={tariff?.rate_per_kwh??""} required/></label><label><FieldLabel htmlFor={`fixed-${tariff?.id??"new"}`}>Fixed charge</FieldLabel><Input id={`fixed-${tariff?.id??"new"}`} name="fixed_charge" inputMode="decimal" defaultValue={tariff?.fixed_charge??"0.00"} required/></label><label><FieldLabel htmlFor={`vat-${tariff?.id??"new"}`}>VAT percent</FieldLabel><Input id={`vat-${tariff?.id??"new"}`} name="vat_percent" inputMode="decimal" defaultValue={tariff?.vat_percent??"7.5"} required/></label></div><label className="mt-4 inline-flex min-h-11 items-center gap-2 text-sm font-semibold"><input name="is_active" type="checkbox" defaultChecked={tariff?.is_active??true}/> Active tariff</label>{message?<p role="alert" className="mt-3 text-sm text-status-overdue">{message}</p>:null}<Button disabled={busy} className="mt-4" type="submit">{tariff?<Save size={16} strokeWidth={1.8}/>:<Plus size={16} strokeWidth={1.8}/>} {busy?"Saving…":tariff?"Save tariff":"Create tariff"}</Button></Card></form>}
