import Link from "next/link";
import { Activity, BookOpenCheck, FileText, Gauge, MessageSquareText, ReceiptText, Settings, ShieldCheck, Users, WalletCards } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import type { Role, User } from "@/lib/types";
import { Brand } from "./brand";
import { LogoutButton } from "./logout-button";

type Nav = { href:string; label:string; icon:LucideIcon };
const customer:Nav[]=[{href:"/dashboard",label:"Dashboard",icon:Gauge},{href:"/bills",label:"My Bills",icon:FileText},{href:"/submit-reading",label:"Submit Reading",icon:Activity},{href:"/complaints",label:"Complaints",icon:MessageSquareText}];
const staff:Nav[]=[{href:"/staff",label:"Dashboard",icon:Gauge},{href:"/staff/meters",label:"Meters",icon:Settings},{href:"/staff/bills",label:"All Bills",icon:ReceiptText},{href:"/staff/complaints",label:"Complaints",icon:MessageSquareText}];
const admin:Nav[]=[{href:"/admin/users",label:"Users",icon:Users},{href:"/admin/tariffs",label:"Tariffs",icon:WalletCards},{href:"/admin/audit",label:"Audit Log",icon:ShieldCheck},{href:"/staff",label:"Billing tools",icon:BookOpenCheck}];
function navFor(role:Role){return role==="customer"?customer:role==="billing_officer"?staff:admin}
export function AppShell({user,children}:{user:User;children:React.ReactNode}){const nav=navFor(user.role);return <div className="app-page lg:grid lg:min-h-dvh lg:grid-cols-[15rem_1fr]"><aside className="no-print hidden border-r border-line bg-paper px-5 py-8 lg:flex lg:flex-col"><Brand/><nav className="mt-10 space-y-1" aria-label="Application navigation">{nav.map(({href,label,icon:Icon})=><Link key={href} href={href} className="flex min-h-11 items-center gap-3 rounded-md px-3 py-2 text-sm font-medium text-info hover:bg-white hover:text-forest"><Icon size={18} strokeWidth={1.8}/>{label}</Link>)}</nav><div className="mt-auto"><p className="truncate px-3 text-sm font-semibold">{user.full_name}</p><p className="truncate px-3 pb-3 font-mono text-[10px] uppercase tracking-wide text-info">{user.role.replaceAll("_"," ")}</p><LogoutButton/></div></aside><div className="min-w-0"><header className="no-print flex min-h-16 items-center justify-between border-b border-line-subtle bg-paper px-6 lg:px-8"><div className="lg:hidden"><Brand/></div><p className="hidden font-mono text-[10px] tracking-[.06em] text-info lg:block">YOUR ELECTRICITY ACCOUNT</p><div className="text-right"><p className="text-sm font-semibold">{user.full_name}</p><p className="font-mono text-[9px] uppercase tracking-[.06em] text-info">{user.role.replaceAll("_"," ")}</p></div></header><main id="main" className="mx-auto w-full max-w-[76rem] px-6 py-8 md:px-8 md:py-10 lg:px-10">{children}</main></div><nav className="safe-bottom no-print fixed inset-x-0 bottom-0 z-40 grid grid-cols-4 border-t border-line bg-white px-2 pt-2 lg:hidden" aria-label="Mobile application navigation">{nav.slice(0,4).map(({href,label,icon:Icon})=><Link key={href} href={href} className="flex min-h-14 flex-col items-center justify-center gap-1 rounded-md px-1 text-[10px] font-medium text-info"><Icon size={19} strokeWidth={1.8}/><span className="max-w-full truncate">{label}</span></Link>)}</nav></div>}
