"use client";
import { useState } from "react";
import { Link2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { FieldError, FieldLabel, Input, Select } from "@/components/ui/field";
import { ApiError, apiRequest } from "@/lib/api";
import type { Meter, Tariff } from "@/lib/types";
export function AssignMeterForm({tariffs}:{tariffs:Tariff[]}){const [errors,setErrors]=useState<Record<string,string>>({});const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setErrors({});setMessage("");const fd=new FormData(e.currentTarget);const data={customer_id:String(fd.get("customer_id")??"").trim(),tariff_id:String(fd.get("tariff_id")??""),meter_number:String(fd.get("meter_number")??"").trim(),opening_reading:String(fd.get("opening_reading")??"").trim()};if(!data.customer_id||!data.tariff_id||!data.meter_number||!data.opening_reading){setMessage("Complete every field.");return}setBusy(true);try{await apiRequest<{meter:Meter}>("/api/v1/staff/meters",{method:"POST",body:JSON.stringify(data)});window.location.assign("/staff/meters")}catch(e){if(e instanceof ApiError){setErrors(e.fields??{});setMessage(e.message)}else setMessage("Meter could not be assigned.")}finally{setBusy(false)}}return <form onSubmit={submit} className="max-w-2xl"><Card className="p-5 md:p-7"><div><FieldLabel htmlFor="customer_id">Customer UUID</FieldLabel><Input id="customer_id" name="customer_id" autoComplete="off" placeholder="Customer user ID" required/><FieldError>{errors.customer_id}</FieldError><p className="mt-2 text-xs leading-5 text-info">Phase 2 currently has no billing-officer customer-search endpoint, so assignment uses the customer UUID required by the API.</p></div><div className="mt-5"><FieldLabel htmlFor="tariff_id">Active tariff</FieldLabel><Select id="tariff_id" name="tariff_id" required defaultValue=""><option value="" disabled>Select tariff</option>{tariffs.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</Select><FieldError>{errors.tariff_id}</FieldError></div><div className="mt-5"><FieldLabel htmlFor="meter_number">Meter number</FieldLabel><Input id="meter_number" name="meter_number" autoComplete="off" required/><FieldError>{errors.meter_number}</FieldError></div><div className="mt-5"><FieldLabel htmlFor="opening_reading">Opening reading (kWh)</FieldLabel><Input id="opening_reading" name="opening_reading" inputMode="decimal" autoComplete="off" required/><FieldError>{errors.opening_reading}</FieldError></div>{message?<p role="alert" className="mt-4 text-sm text-status-overdue">{message}</p>:null}<Button disabled={busy} className="mt-6 w-full sm:w-auto" type="submit"><Link2 size={17} strokeWidth={1.8}/>{busy?"Assigning…":"Assign meter"}</Button></Card></form>}
