"use client";
import { useState } from "react";
import { Send } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { FieldError, FieldLabel, Input, Select, Textarea } from "@/components/ui/field";
import { ApiError, apiRequest } from "@/lib/api";
import { complaintSchema } from "@/lib/schemas";
import type { Bill, Complaint } from "@/lib/types";
import { monthLabel, formatNaira } from "@/lib/format";
export function ComplaintForm({bills}:{bills:Bill[]}){const [errors,setErrors]=useState<Record<string,string>>({});const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setErrors({});setMessage("");const fd=new FormData(e.currentTarget);const data={category:String(fd.get("category")??""),subject:String(fd.get("subject")??""),message:String(fd.get("message")??""),bill_id:String(fd.get("bill_id")??"")||undefined};const parsed=complaintSchema.safeParse(data);if(!parsed.success){setErrors(Object.fromEntries(parsed.error.issues.map(i=>[String(i.path[0]),i.message])));return}setBusy(true);try{await apiRequest<{complaint:Complaint}>("/api/v1/me/complaints",{method:"POST",body:JSON.stringify(parsed.data)});window.location.assign("/complaints")}catch(e){if(e instanceof ApiError){setErrors(e.fields??{});setMessage(e.message)}else setMessage("Complaint could not be submitted.")}finally{setBusy(false)}}return <form onSubmit={submit} className="max-w-2xl"><Card className="p-5 md:p-7"><div><FieldLabel htmlFor="category">Category</FieldLabel><Select id="category" name="category" defaultValue="bill_dispute"><option value="bill_dispute">Bill dispute</option><option value="meter_reading">Meter reading</option><option value="payment">Payment</option><option value="other">Other</option></Select><FieldError>{errors.category}</FieldError></div><div className="mt-5"><FieldLabel htmlFor="bill_id">Related bill (optional)</FieldLabel><Select id="bill_id" name="bill_id" defaultValue=""><option value="">No bill selected</option>{bills.map(b=><option key={b.id} value={b.id}>{monthLabel(b.billing_month)} · {formatNaira(b.total_amount)}</option>)}</Select><FieldError>{errors.bill_id}</FieldError></div><div className="mt-5"><FieldLabel htmlFor="subject">Subject</FieldLabel><Input id="subject" name="subject" maxLength={160} required/><FieldError>{errors.subject}</FieldError></div><div className="mt-5"><FieldLabel htmlFor="message">Message</FieldLabel><Textarea id="message" name="message" maxLength={4000} required/><FieldError>{errors.message}</FieldError><p className="mt-2 text-xs text-info">Do not include passwords, card numbers or other secrets.</p></div>{message?<p role="alert" className="mt-4 text-sm text-status-overdue">{message}</p>:null}<Button disabled={busy} className="mt-6 w-full sm:w-auto" type="submit"><Send size={17} strokeWidth={1.8}/>{busy?"Submitting…":"Submit complaint"}</Button></Card></form>}
