"use client";
import { useState } from "react";
import { GaugeCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { FieldError, FieldLabel, Input, Select } from "@/components/ui/field";
import { ApiError, apiRequest } from "@/lib/api";
import { readingSchema } from "@/lib/schemas";
import type { Bill, Meter } from "@/lib/types";
export function ReadingForm({meters}:{meters:Meter[]}){const [errors,setErrors]=useState<Record<string,string>>({});const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setErrors({});setMessage("");const fd=new FormData(e.currentTarget);const data={meter_id:String(fd.get("meter_id")??""),reading:String(fd.get("reading")??"")};const parsed=readingSchema.safeParse(data);if(!parsed.success){setErrors(Object.fromEntries(parsed.error.issues.map(i=>[String(i.path[0]),i.message])));return}setBusy(true);try{const body=await apiRequest<{bill:Bill}>("/api/v1/me/readings",{method:"POST",body:JSON.stringify(parsed.data)});window.location.assign(`/bills/${body.bill.id}`)}catch(e){if(e instanceof ApiError){setErrors(e.fields??{});setMessage(e.message)}else setMessage("Reading could not be submitted.")}finally{setBusy(false)}}return <form onSubmit={submit} className="max-w-2xl"><Card className="p-5 md:p-7"><div><FieldLabel htmlFor="meter_id">Meter</FieldLabel><Select id="meter_id" name="meter_id" required defaultValue=""><option value="" disabled>Select your meter</option>{meters.map(m=><option key={m.id} value={m.id}>{m.meter_number}</option>)}</Select><FieldError>{errors.meter_id}</FieldError></div><div className="mt-5"><FieldLabel htmlFor="reading">Current reading (kWh)</FieldLabel><Input id="reading" name="reading" inputMode="decimal" autoComplete="off" placeholder="e.g. 6842.0" required/><FieldError>{errors.reading}</FieldError><p className="mt-2 text-xs leading-5 text-info">A reading cannot be lower than the previous reading. Consumption over 50,000 kWh is held for manual verification.</p></div>{message?<p role="alert" className="mt-4 text-sm text-status-overdue">{message}</p>:null}<Button disabled={busy||!meters.length} className="mt-6 w-full sm:w-auto" type="submit"><GaugeCircle size={17} strokeWidth={1.8}/>{busy?"Submitting…":"Submit reading"}</Button></Card></form>}
