import { Suspense } from "react";
import { Card } from "@/components/ui/card";
import { PageHeader } from "@/components/ui/page-header";
import { Pager } from "@/components/ui/pager";
import { UrlFilters } from "@/components/filters/url-filters";
import { serverApi } from "@/lib/server-api";
import { formatDate } from "@/lib/format";
import type { AuditLog, PageResult } from "@/lib/types";
type SP=Promise<Record<string,string|string[]|undefined>>;const one=(x:string|string[]|undefined)=>Array.isArray(x)?x[0]:x;
export default async function Audit({searchParams}:{searchParams:SP}){const s=await searchParams;const q=new URLSearchParams();if(one(s.action))q.set("action",one(s.action)!);if(one(s.page))q.set("page",one(s.page)!);const data=await serverApi<PageResult<AuditLog>>(`/api/v1/admin/audit?${q}`);return <div className="space-y-7"><PageHeader eyebrow="APPEND-ONLY LOG" title="Audit Log" description="Review security-sensitive events such as logins, denied access, meter/reading actions, payments, tariff changes and role changes."/><Suspense><UrlFilters extra={{key:"action",label:"Action",options:[{value:"login_success",label:"Login success"},{value:"login_failed",label:"Login failed"},{value:"payment_recorded",label:"Payment recorded"},{value:"tariff_updated",label:"Tariff updated"},{value:"user_role_status_changed",label:"User role/status changed"},{value:"idor_bill_denied",label:"IDOR denied"}]}}/></Suspense><div className="space-y-2">{data.items.map(a=><Card key={a.id} className="p-4"><div className="grid gap-3 md:grid-cols-[11rem_1fr_12rem]"><div><p className="font-mono text-[10px] font-bold text-forest">{a.action}</p><p className="mt-1 text-xs text-info">{formatDate(a.created_at)}</p></div><div><p className="text-sm"><span className="text-info">Actor:</span> <span className="data-number break-all text-xs">{a.actor_id??"system"}</span></p><p className="mt-1 text-sm"><span className="text-info">Target:</span> {a.target_type??"—"} <span className="data-number text-xs">{a.target_id??""}</span></p></div><p className="data-number text-xs text-info">IP {a.ip_address??"—"}</p></div></Card>)}</div><Pager page={data.page} pages={data.pages} pathname="/admin/audit" params={{action:one(s.action)}}/></div>}
