"use client";
import { useState } from "react";
import { useSearchParams } from "next/navigation";
import { LogIn } from "lucide-react";
import { Button } from "@/components/ui/button";
import { FieldError, FieldLabel, Input } from "@/components/ui/field";
import { ApiError, apiRequest } from "@/lib/api";
import { loginSchema } from "@/lib/schemas";
import type { User } from "@/lib/types";
export function LoginForm(){const search=useSearchParams();const [errors,setErrors]=useState<Record<string,string>>({});const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setErrors({});setMessage("");const fd=new FormData(e.currentTarget);const data={email:String(fd.get("email")??""),password:String(fd.get("password")??"")};const parsed=loginSchema.safeParse(data);if(!parsed.success){setErrors(Object.fromEntries(parsed.error.issues.map(i=>[String(i.path[0]),i.message])));return}setBusy(true);try{const next=search.get("next");const body=await apiRequest<{user:User;next:string|null}>("/api/v1/auth/login",{method:"POST",body:JSON.stringify({...parsed.data,next}),authRedirect:false});const fallback=body.user.role==="admin"?"/admin/users":body.user.role==="billing_officer"?"/staff":"/dashboard";window.location.assign(body.next||fallback)}catch(err){if(err instanceof ApiError){setErrors(err.fields??{});setMessage(err.message)}else setMessage("Unable to log in.")}finally{setBusy(false)}}return <form onSubmit={submit} className="auth-form" noValidate><p className="font-mono text-[10px] font-bold tracking-[.08em] text-forest">GOOD TO SEE YOU AGAIN</p><h1 className="display">Welcome back.</h1><p className="mt-2 text-sm leading-6 text-info">Let’s get your bills sorted. Sign in with your email and password.</p>{search.get("registered")==="1"?<p role="status" className="mt-5 rounded-md border border-line bg-sage-light p-3 text-sm text-forest">✓ Account created. Sign in to explore your dashboard.</p>:null}{message?<p role="alert" className="mt-5 rounded-md border border-[#F3B8B2] bg-[#FFF0EE] p-3 text-sm text-status-overdue">{message}</p>:null}<div className="mt-6"><FieldLabel htmlFor="email">Email address</FieldLabel><Input id="email" name="email" type="email" autoComplete="email" inputMode="email" required/><FieldError>{errors.email}</FieldError></div><div className="mt-5"><FieldLabel htmlFor="password">Password</FieldLabel><Input id="password" name="password" type="password" autoComplete="current-password" required/><FieldError>{errors.password}</FieldError></div><Button aria-busy={busy} disabled={busy} className="mt-6 w-full" type="submit">{busy?"Signing in…":<><LogIn size={17} strokeWidth={1.8}/>Log in</>}</Button><a className="mt-5 block text-center text-sm font-semibold text-forest hover:underline" href="/register">New here? Create an account</a></form>}
